spring.application.name=zonas-espacios
server.port=8081

# CONFIGURACION DE LA CONEXION A POSTGRESQL (Cambiado desde MySQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/zonasbd
spring.datasource.username=postgres
spring.datasource.password=Admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE HIBERNATE / JPA PARA POSTGRES
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION DE SEGURIDAD (JWT)
security.jwt.secret=${JWT_SECRET:SecretKeyForJWTAuthenticationWhichIsVeryLongAndSecureEnoughToSatisfyHMACSHA256}

# CONFIGURACION DE RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
rabbitmq.exchange=${RABBITMQ_EXCHANGE:exchange_audit}
rabbitmq.routingkey=${RABBITMQ_ROUTING_KEY:routing_audit}