spring.application.name=usuarios
server.port=8080

# CONFIGURACION DE BASE DE DATOS (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:usuarios_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION DEL POOL DE CONEXIONES (HIKARI)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime=1800000

# CONFIGURACION DE SEGURIDAD (JWT)
security.jwt.secret=${JWT_SECRET:SecretKeyForJWTAuthenticationWhichIsVeryLongAndSecureEnoughToSatisfyHMACSHA256}
security.jwt.expiration-time=${JWT_EXPIRATION_MS:86400000}

# CONFIGURACION DE RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}
rabbitmq.exchange=${RABBITMQ_EXCHANGE:exchange_audit}
rabbitmq.routingkey=${RABBITMQ_ROUTING_KEY:routing_audit}